#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 10-valkey
PROCESS_NAME="valkey"

check_container_initialized
check_service_initialized init

liftoff

if var_true "${ENABLE_LOGS}" ; then
    valkey_logs=" --logfile ${LOG_PATH}/${LOG_FILE}"
fi

if var_true "${ENABLE_PERSISTENCE}" ; then
   valkey_persistence="--appendonly yes"
fi

if var_true "${ENABLE_SOCKET}" ; then
	valkey_socket="--unixsocket ${SOCKET_PATH}/${SOCKET_FILE} --unixsocketperm ${SOCKET_PERMISSIONS}"
fi

transform_file_var VALKEY_PASS
## Valkey Setup
	# first arg is `-f` or `--some-option`
	# or first arg is `something.conf`
	if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
		set -- valkey-server "$@"
	fi

	# allow the container to be started with `--user`
	if [ "$1" = 'valkey-server' -a "$(id -u)" = '0' ]; then
		chown -R valkey .
		exec su-exec valkey "$0" "$@"
	fi

print_start "Starting Valkey ${VALKEY_VERSION}"
exec s6-setuidgid valkey valkey-server --dir "${DATA_PATH}" \
                                     ${VALKEY_PASS:+--requirepass $VALKEY_PASS} \
                                     --loglevel "${LOG_LEVEL}" \
                                     --port ${VALKEY_PORT} \
				     				${valkey_persistence} ${valkey_logs} ${valkey_socket}
