services:

  valkey-app:
    image: tiredofit/valkey
    container_name: valkey-app
    volumes:
      - ./data:/data/db
      #- ./logs:/data/logs
    environment:
      - CONTAINER_NAME=valkey-app

      - ENABLE_LOGS=FALSE
      - VALKEY_PASS=password
    networks:
      - services
    restart: always

networks:
  services:
    external: true

